version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
