name: Dependabot

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          target: minor
          github-token: ${{ secrets.PUSH_TOKEN }}
